name: Testing Pull Requests to Niffler Dev
on:
  pull_request:
    branches: [dev]

jobs:
  run_unit_tests:
    name: Run Unit Tests on PR
    runs-on: ubuntu-latest
    container: "centos:latest"
    steps:
      - uses: actions/checkout@master
      - name: Install Python 3
        run: |
          yum update -y -q
          yum install -q -y python3 
          yum install -q -y python3-pip unzip
      - name: Install Dependencies
        run: |
          pip3 install -U pip
          pip3 install -r ./requirements-dev.txt
          unzip ./tests/data.zip -d ./tests/
      - name: Run Tests
        run: |
          echo "Running Unit Tests"
          pytest ./tests/unit

  run_integration_tests:
    name: Run Integration Tests on PR
    runs-on: ubuntu-latest
    container: "centos:latest"
    steps:
      - uses: actions/checkout@master
      - name: Install Python 3
        run: |
          yum update -y -q
          yum install -q -y python3 
          yum install -q -y python3-pip unzip
      - name: Install Dependencies
        run: |
          pip3 install -U pip
          pip3 install -r ./requirements-dev.txt
          unzip ./tests/data.zip -d ./tests/
      - name: Run Tests
        run: |
          echo "Running Integration Tests"
          pytest ./tests/integration
